FROM python:3.8-slim

ENV AWS_DEFAULT_REGION=us-east-1
ENV PYTHONUNBUFFERED=1

LABEL maintainer="https://github.com/jonrau1" \
    version="2.0" \
    license="GPL-3.0" \
    description="Continuously monitor your AWS services for configurations that can lead to degradation of confidentiality, integrity or availability. All results will be sent to Security Hub for further aggregation and analysis."

COPY requirements.txt /tmp/
COPY requirements-dev.txt /tmp/
COPY audit_controller.py .

RUN pip3 install -r /tmp/requirements-dev.txt

CMD pytest auditors