AWSTemplateFormatVersion: 2010-09-09
Description: >- 
  ElectricEye StackSet deploys an IAM Role with all possible ElectricEye permissions that trust a central security account for AWS Organizations-wide assessments
Parameters:
  # Security Account ID
  CentralSecurityAccount:
    Description: Account ID for your Security Account
    Type: String
Resources:
  #######
  # IAM #
  #######
  CrossAccountElectricEyeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CrossAccountElectricEyeRole
      Description: >-
        Allows the Central Security Account access to all AWS APIs used for ElectricEye CSPM and EASM assessments - Managed by CloudFormation StackSets
      Policies:
      - PolicyName: CrossAccountElectricEyeRolePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - athena:GetWorkGroup
                - athena:ListWorkGroups
                - airflow:GetEnvironment
                - airflow:ListEnvironments
                - autoscaling:DescribeAutoScalingGroups
                - cloudtrail:DescribeTrails
                - cloudtrail:ListTrails
                - kms:DescribeKey
                - kms:Decrypt
                - access-analyzer:ListAnalyzers
                - ec2:Describe*
                - kms:ListKeys
                - cloudformation:ListStacks
                - kinesisanalytics:ListApplications
                - ec2:Get*
                - cassandra:Select
                - kms:ListAliases
                - ram:GetResourceShares
                - cloudwatch:GetMetricData
                - qldb:ListLedgers
                - qldb:ListJournalS3Exports
                - rds:DescribeEventSubscriptions
                - ssm:ListDocuments
                - ssm:ListAssociations
                - ssm:DescribeDocumentPermission
                - ecs:ListClusters
                - ecs:DescribeClusters
                - elasticloadbalancing:DescribeLoadBalancers
                - kinesis:ListStreams
                - cognito-idp:DescribeUserPool
                - dynamodb:DescribeTable
                - dynamodb:DescribeContinuousBackups
                - dynamodb:DescribeTimeToLive
                - dynamodb:ListTables
                - dax:DescribeParameters
                - dax:DescribeClusters
                - detective:ListGraphs
                - shield:DescribeSubscription
                - acm:DescribeCertificate
                - acm:ListCertificates
                - elasticmapreduce:DescribeCluster
                - elasticmapreduce:DescribeSecurityConfiguration
                - elasticmapreduce:GetBlockPublicAccessConfiguration
                - elasticmapreduce:ListClusters
                - firehose:DescribeDeliveryStream
                - firehose:ListDeliveryStreams
                - glue:GetSecurityConfiguration
                - glue:GetResourcePolicy
                - glue:GetCrawler
                - glue:GetDataCatalogEncryptionSettings
                - glue:ListCrawlers
                - appmesh:DescribeMesh
                - appmesh:DescribeVirtualNode
                - appmesh:ListMeshes
                - appmesh:ListVirtualNodes
                - support:DescribeTrustedAdvisorCheckResult
                - support:DescribeTrustedAdvisorChecks
                - health:DescribeEvents
                - iam:GetAccountPasswordPolicy
                - iam:ListUsers
                - iam:ListAccessKeys
                - iam:ListMfaDevices
                - iam:ListUserPolicies
                - iam:ListAttachedUserPolicies
                - iam:ListServerCertificates
                - rolesanywhere:ListProfiles
                - rolesanywhere:ListTrustAnchors
                - rolesanywhere:ListCrls
                - macie2:GetMacieSession
                - managedblockchain:Get*
                - managedblockchain:List*
                - mq:Describe*
                - mq:List*
                - memorydb:Describe*
                - license-manager:GetLicenseConfiguration
                - license-manager:ListLicenseConfigurations
                - ecr:DescribeImages
                - ecr:GetRegistryPolicy
                - ecr:DescribeRegistry
                - securityhub:GetFindings
                - codebuild:ListProjects
                - codebuild:ListSourceCredentials
                - workspaces:DescribeWorkspaces
                - ecr:GetLifecyclePolicy
                - sns:ListSubscriptionsByTopic
                - appstream:DescribeImages
                - kafka:DescribeCluster
                - cognito-idp:ListUserPools
                - cloudformation:DescribeStacks
                - elasticloadbalancing:DescribeLoadBalancerAttributes
                - elasticloadbalancing:DescribeListeners
                - elasticbeanstalk:DescribeEnvironments
                - elasticbeanstalk:DescribeConfigurationSettings
                - ds:ListLogSubscriptions
                - s3:GetObject
                - eks:DescribeCluster
                - eks:ListClusters
                - elasticache:DescribeCacheClusters
                - shield:DescribeDRTAccess
                - secretsmanager:ListSecrets
                - s3:GetLifecycleConfiguration
                - appstream:DescribeUsers
                - kafka:ListClusters
                - shield:DescribeProtection
                - sagemaker:DescribeNotebookInstance
                - sns:ListTopics
                - elasticfilesystem:DescribeFileSystems
                - apigateway:GET
                - rds:DescribeDB*
                - rds:DescribeEventCategories
                - s3:ListBucket
                - backup:DescribeProtectedResource
                - s3:GetEncryptionConfiguration
                - s3:GetBucketLogging
                - s3:GetBucketPolicy
                - s3:GetBucketPolicyStatus
                - s3:GetBucketVersioning
                - es:DescribeElasticsearchDomain
                - ssm:DescribeInstance*
                - redshift:DescribeLoggingStatus
                - redshift:DescribeClusters
                - redshift:DescribeClusterParameters
                - appstream:DescribeFleets
                - ecr:DescribeRepositories
                - sagemaker:DescribeEndpoint
                - workspaces:DescribeWorkspaceDirectories
                - sagemaker:ListNotebookInstances
                - codebuild:BatchGetProjects
                - guardduty:ListDetectors
                - dms:DescribeReplicationInstances
                - sns:GetTopicAttributes
                - route53:ListTrafficPolicyInstancesByHostedZone
                - route53:ListHostedZones
                - route53:ListResourceRecordSets
                - route53:ListQueryLoggingConfigs
                - sagemaker:DescribeModel
                - kinesis:DescribeStream
                - sns:ListSubscriptions
                - es:ListDomainNames
                - s3:GetAccountPublicAccessBlock
                - s3:ListAllMyBuckets
                - ssm:GetP*
                - wafv2:ListWebACLs
                - wafv2:GetLoggingConfiguration
                - wafv2:GetWebACL
                - wafv2:GetWebACLForResource
                - cloudfront:ListDistributions
                - sagemaker:ListModels
                - ds:DescribeDirectories
                - securityhub:BatchImportFindings
                - sagemaker:ListEndpoints
                - ecr:GetRepositoryPolicy
                - sqs:ListQueues
                - sqs:GetQueueAttributes
                - globalaccelerator:ListAccelerators
                - globalaccelerator:ListListeners
                - globalaccelerator:ListEndpointGroups
                - xray:GetEncryptionConfig
                - cloud9:DescribeEnvironments
                - cloud9:ListEnvironments
                - cloudsearch:DescribeDomainEndpointOptions
                - cloudsearch:DescribeDomains
                - lambda:GetFunction
                - lambda:GetLayerVersion
                - lambda:GetLayerVersionPolicy
                - lambda:GetPolicy
                - lambda:ListFunctions
                - lambda:ListLayerVersions
                - lambda:ListLayers
                - ecs:DescribeTaskDefinition
                - ecs:ListTaskDefinitionFamilies
                - ecs:ListTaskDefinitions
                - datasync:DescribeAgent
                - datasync:DescribeTask
                - datasync:ListAgents
                - datasync:ListTasks
                - fsx:DescribeBackups
                - fsx:DescribeFileSystems
                - amplify:ListApps
                - elasticfilesystem:DescribeFileSystemPolicy
                - codeartifact:GetDomainPermissionsPolicy
                - codeartifact:ListDomains
                - codeartifact:ListRepositories
                - codeartifact:GetRepositoryPermissionsPolicy
                - shield:ListAttacks
                - cloudhsm:DescribeClusters
                - cloudhsm:DescribeBackups
                - iam:ListRolePolicies
                - iam:ListRoles
                - iam:GetRolePolicy
                - iam:GetUserPolicy
                - iam:ListGroupPolicies
                - iam:ListGroups
                - iam:GetGroupPolicy
                - iam:ListPolicies
                - iam:GetPolicyVersion
                - route53resolver:ListResolverQueryLogConfigAssociations
                - route53resolver:GetFirewallConfig
                - route53resolver:ListResolverDnssecConfigs
                - route53resolver:ListFirewallRuleGroupAssociations
                - imagebuilder:ListImagePipelines
                - imagebuilder:ListImageRecipes
                - imagebuilder:GetImageRecipe
                - imagebuilder:GetImagePipeline
                - cloudfront:GetDistribution
              Resource: "*"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub '${CentralSecurityAccount}'
            Action:
              - sts:AssumeRole
      Tags: 
        - 
          Key: Name
          Value: CrossAccountElectricEyeRole
        - 
          Key: Service
          Value: ElectricEye
# END