# This TOML document provides configuration for all of ElectricEye, from credentials to regions to accounts 
# as well as global settings, filenames, and other directives that can be used by ElectricEye

title = "ElectricEye Configuration"

[global]

# Match this to [regions_and_accounts.aws.aws_account_targets] to specify if you want to run ElectricEye
# against a list of Accounts, list of Accounts within specific OUs, or every Account in an AWS Organization

aws_multi_account_target_type = "Accounts" # VALID CHOICES: Accounts | OU | Organization

# Specifies the location of where credentials are stored and will be retrieved from
# if you specify "CONFIG_FILE" that means you can provide the value within the option itself

credentials_location = "AWS_SSM" # VALID CHOICES: AWS_SSM | AWS_SECRETS_MANAGER | CONFIG_FILE

[regions_and_accounts]

    [regions_and_accounts.aws]
    
    # A list of Accounts, OU ID's, or an Organizations Principal ID - must match global.aws_multi_account_target_type
    # if a value is not provided the current Account will be used unless "Organization" is specified
    
    aws_account_targets = []
    
    # If left blank, the *current AWS Region* is used. You can provide a list of AWS Regions or simply "All"
    
    aws_regions_selection = [] # VALID CHOICES: [] | ["All"] | list of regions e.g., ["us-east-1", "us-east-2"]

    # The NAME of the AWS IAM Role deployed to aws_account_targets - must be the same for all Accounts
    # including your current Account
    
    aws_electric_eye_iam_role_name = ""

    [regions_and_accounts.gcp]
    
    # Provide a list of GCP Project ID's - your Service Account must be associated with all of the Projects listed
    
    gcp_project_ids = []

[credentials]

# ***IMPORTANT*** all passwords, API keys, and sensitive credentials (that end with '_value') should match the value
# of [global.credentials_location], for instance, if you specified "AWS_SSM" ensure that the '_value' option is the name
# of an AWS SecureString Parameter that contains the value to be retrieved

    [credentials.azure]
    azure_sp_client_id_value = ""
    azure_sp_tenant_id_value = ""
    azure_sp_client_secret_id_value = ""

    [credentials.gcp]
    gcp_service_account_json_payload_value = ""

    [credentials.github]
    gh_personal_access_token_value = ""

    [credentials.m365]
    m365_ent_app_client_id_value = ""
    m365_ent_app_tenant_id_value = ""
    m365_ent_app_client_secret_id_value = ""

    [credentials.servicenow]

    # The *name* of your Instance, for example, if its URL is "https://dev90210.service-now.com/" the name is "dev90210"
    
    servicenow_instance_name = ""

    # Geographic location of your Instance which will be provided to `ProductFields.AssetRegion` within the Electriceye Findings
    # this is typically "us", "eu", or "ap" and may differ for Federal instances

    servicenow_instance_region = ""

    # The name of the ServiceNow User with permissions that will be used by the PySNOW Client

    servicenow_sspm_username = ""

    # The location (or actual contents) of the Password for the User specified in `servicenow_instance_name`
    # this location must match the value of `global.credentials_location` e.g., if you specify "AWS_SSM" then
    # the value for this variable should be the name of the SSM SecureString Parameter

    servicenow_sspm_password_value = ""

    # The threshold for when to create a failing finding for the "Servicenow_Users_Auditor" Check for failed login-in
    # attempts by active users in your Instance

    servicenow_failed_login_breaching_rate = "5"